// lib/icon_mapping.dart
import 'package:flutter/material.dart';

/// Mapping for the icons you provided
const Map<String, IconData> iconMapping = {
  'medical_services': Icons.medical_services,
  'visibility': Icons.visibility,
  'local_hospital': Icons.local_hospital,
  'pregnant_woman': Icons.pregnant_woman,
  'healing': Icons.healing,
  'straighten': Icons.straighten,
  'favorite': Icons.favorite,
  'chemistry': Icons.science,
  'water_drop': Icons.water_drop,
  'calculate': Icons.calculate,
  'monitor_heart': Icons.monitor_heart,
  'fitness_center': Icons.fitness_center,
  'insights': Icons.insights,
  'local_drink': Icons.local_drink,
  // 'sugar': Icons.gluc,
  'opacity': Icons.opacity,
  'bloodtype': Icons.bloodtype,
  'device_thermostat': Icons.device_thermostat,
  'list_alt': Icons.list_alt,
  // 'virus': Icons.virus,
  'scatter_plot': Icons.scatter_plot,
  'battery_charging_full': Icons.battery_charging_full,
  // 'protein': Icons.protein,
  'search': Icons.search,
  'bug_report': Icons.bug_report,
  'nature': Icons.nature,
  'science': Icons.science,
  'speed': Icons.speed,
  // 'surgical_mask': Icons.surgical_mask,
  'content_cut': Icons.content_cut,
  'clean_hands': Icons.clean_hands,
  // 'medical_cross': Icons.medical_cross,
  // 'surgical': Icons.surgical,
  'female': Icons.female,
  'biotech': Icons.biotech,
};
